const diceBag = {
  fourByFourDice: [
    "AAEEGN",
    "ABBJOO",
    "ACHOPS",
    "AFFKPS",
    "AOOTTW",
    "CIMOTU",
    "DEILRX",
    "DELRVY",
    "DISTTY",
    "EEGHNW",
    "EEINSU",
    "EHRTVW",
    "EIOSST",
    "ELRTTY",
    ["H", "I", "M", "N", "U", "Qu"],
    "HLNNRZ"
  ],
  fiveByFiveDice: [
    "AAAFRS",
    "AAEEEE",
    "AAFIRS",
    "ADENNN",
    "AEEEEM",
    "AEEGMU",
    "AEGMNN",
    "AFIRSY",
    "BBJKXZ",
    "CCENST",
    "EIILST",
    "CEIPST",
    "DDHNOT",
    "DHHLOR",
    "DHHNOW",
    "DHLNOR",
    "EIIITT",
    "EILPST",
    "EMOTTT",
    "ENSSSU",
    ["Qu", "In", "Th", "Er", "He", "An"], // Alternate cube is: FIPRSY
    "GORRVW",
    "IPRSYY",
    "NOOTUW",
    "OOOTTU"
  ],
  sixBySixDice: [
    "AAAFRS",
    "AAEEEE",
    "AAEEOO",
    "AAFIRS",
    "ABDEIO",
    "ADENNN",
    "AEEEEM",
    "AEEGMU",
    "AEGMNN",
    "AEILMN",
    "AEINOU",
    "AFIRSY",
    ["An", "Er", "He", "In", "Qu", "Th"],
    "BBJKXZ",
    "CCENST",
    "CDDLNN",
    "CEIITT",
    "CEIPST",
    "CFGNUY",
    "DDHNOT",
    "DHHLOR",
    "DHHNOW",
    "DHLNOR",
    "EHILRS",
    "EIILST",
    "EILPST",
    "EIO###",
    "EMTTTO",
    "ENSSSU",
    "GORRVW",
    "HIRSTV",
    "HOPRST",
    "IPRSYY",
    ["J", "K", "Qu", "W", "X", "Z"],
    "NOOTUW",
    "OOOTTU"
  ]
};

export default diceBag;
